# Given an array of strings arr[], find the maximum possible length
#  of a string of distinct characters that can be generated by concatenating of 
# the subsequence of the given array.

def check(s):
     
    uniqueSet = set()
  
    # Check for repetition in
    # characters
    for letter in s:
        if letter not in uniqueSet:
            uniqueSet.add(letter)
  
    return len(uniqueSet)